### ISSUE TITLE
Your noob test need some discussion

### ISSUE THREAD

**Issue by zgrimshell** [james-at-purism/test#1]
Discussion started

**Comment by james-at-purism** [comment]
consider it started :)

**Comment by zgrimshell** [comment]
Consider it finished, so close and comment on the issue.

**Comment by zgrimshell** [comment]
Also @james-at-purism you can mention me in comment (if you want me to get direct mail). Same as CC in mails

**Comment by james-at-purism** [comment]
Noob test complete
